name: Build the multi-platform NPM package.
on:
  workflow_dispatch:

jobs:
  build:
    name: Builds the project for all supported platforms.
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Run the build script.
        run: ./build.sh

      - name: Assemble the NPM package
        run: |
          cd npmpk
          npm pack

      - name: Upload the assembled NPM package as a workflow artifact
        uses: actions/upload-artifact@v2
        with:
          name: NPM package
          path: npmpk/proggy-*.tgz
          if-no-files-found: error