name: Build the multi-platform NPM package.
on:
  workflow_dispatch:

env:
  DOTNET_PROJECT: proggy
  DOTNET_VERSION: 5.0.x
  NPM_PACKAGE_PROJECT: npmpk
  RUNTIME_IDS: linux-x64 osx-x64 win-x64 win-x86

jobs:
  build:
    name: Builds the '${{ env.DOTNET_PROJECT }}' project for all supported platforms.
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build the '${{ env.DOTNET_PROJECT }}' project.
        run: ./build.sh ${{ env.RUNTIME_IDS }}

      - name: Assemble the NPM package
        run: |
          cd ${{ env.NPM_PACKAGE_PROJECT }}
          npm pack

      - name: Upload NPM package
        uses: actions/upload-artifact@v2
        with:
          name: ${{ varialbes.DOTNET_PROJECT }}'s NPM package
          path: npmpk/${{ env.DOTNET_PROJECT }}-*.tgz
          if-no-files-found: error