name: Build the multi-platform NPM package.
on:
  workflow_dispatch:

variables:
  - name: project
    value: proggy
  - name: dotnetver
    value: 5.0.x
  - name: npmproj
    value: npmpk
  - name: runtimeids
    value: linux-x64 osx-x64 win-x64 win-x86

jobs:
  build:
    name: Builds the '${{ variables.project }}' project for all supported platforms.
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ variables.dotnetver }}

      - name: Build the '${{ variables.project }}' project.
        run: ./build.sh ${{ variables.runtimeids }}

      - name: Assemble the NPM package
        run: |
          cd ${{ variables.npmproj }}
          npm pack

      - name: Upload NPM package
        uses: actions/upload-artifact@v2
        with:
          name: ${{ varialbes.project }}'s NPM package
          path: npmpk/${{ variables.project }}-*.tgz
          if-no-files-found: error